services:
  - type: web
    name: translator-notes-backend
    env: python
    buildCommand: |
      sudo apt-get update && sudo apt-get install -y sqlite3
      pip install -r backend/requirements.txt
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: "/opt/render/project/src/backend"
